"""empty message

Revision ID: 53152b1c318e
Revises: 191d901d8350
Create Date: 2020-07-20 22:24:12.106258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53152b1c318e'
down_revision = '191d901d8350'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('start_time', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Show', 'start_time')
    # ### end Alembic commands ###
