"""empty message

Revision ID: a21b45db2858
Revises: f150850ff5be
Create Date: 2020-07-20 04:14:36.907398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a21b45db2858'
down_revision = 'f150850ff5be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('facebook_link', sa.String(length=120), nullable=True))
    op.add_column('Venue', sa.Column('facebook_link', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'facebook_link')
    op.drop_column('Artist', 'facebook_link')
    # ### end Alembic commands ###
